Better handling of errors during build or deployment

diff --git a/java/target/start b/java/target/start
--- a/java/target/start
+++ b/java/target/start
@@ -8,7 +8,15 @@
 if [[ $BUILD_BEFORE_START == "True" ]]; then
     `which mail` -r simon.marcel.pamies@sap.com -s "Build of $SERVER_NAME starting" $BUILD_COMPLETE_NOTIFY
     `pwd`/shouldIBuildOrShouldIGo.sh &> last_automatic_build.log
-    `which mail` -r simon.marcel.pamies@sap.com -s "Build of $SERVER_NAME complete" $BUILD_COMPLETE_NOTIFY < last_automatic_build.log
+     STATUS=$?
+     if [ $STATUS -eq 0 ]; then
+        echo "Deployment Successful"
+        `which mail` -s "Build of $SERVER_NAME complete" $BUILD_COMPLETE_NOTIFY < last_automatic_build.log
+     else
+        echo "Deployment Failed"
+        `which mail` -s "Build of $SERVER_NAME failed" $BUILD_COMPLETE_NOTIFY < last_automatic_build.log
+        exit
+     fi 
 fi
 
 PARAM=$@
