b5938: Remove more tabs

diff --git a/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers b/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers
--- a/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers
+++ b/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers
@@ -17,14 +17,14 @@ if [ "${curl_exit_code}" = "0" ]; then
       ssh_key_curl_exit_code=$?
       if [ "${ssh_key_curl_exit_code}" = "0" ]; then
         echo "${ssh_key_curl_output}" | jq -r '.[].publicKey'
-	ssh_key_jq_exit_code=$?
-	if [ "${ssh_key_jq_exit_code}" != "0" ]; then
-	  EXIT_CODE=${ssh_key_jq_exit_code}
-	  logger -t sailing "Couldn't parse response of get_ssh_keys_owned_by_user; jq exit code ${ssh_key_jq_exit_code}"
-	fi
+    ssh_key_jq_exit_code=$?
+    if [ "${ssh_key_jq_exit_code}" != "0" ]; then
+      EXIT_CODE=${ssh_key_jq_exit_code}
+      logger -t sailing "Couldn't parse response of get_ssh_keys_owned_by_user; jq exit code ${ssh_key_jq_exit_code}"
+    fi
       else
         EXIT_CODE=${ssh_key_curl_exit_code}
-	logger -t sailing "Couldn't get response of get_ssh_keys_owned_by_user; curl exit code ${ssh_key_corl_exit_code}"
+    logger -t sailing "Couldn't get response of get_ssh_keys_owned_by_user; curl exit code ${ssh_key_corl_exit_code}"
       fi
     done | sort -u )
     logger -t sailing "Obtained public keys: ${public_keys}"
diff --git a/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers_if_changed b/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers_if_changed
--- a/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers_if_changed
+++ b/configuration/environments_scripts/repo/usr/local/bin/update_authorized_keys_for_landscape_managers_if_changed
@@ -13,7 +13,7 @@ if [ "${curl_exit_code}" = "0" ]; then
     if [ -f "${LAST_CHANGE_FILE}" ]; then
       PREVIOUS_CHANGE=$(cat "${LAST_CHANGE_FILE}")
       if [ -z ${PREVIOUS_CHANGE} ]; then
-	PREVIOUS_CHANGE=0
+    PREVIOUS_CHANGE=0
       fi
     else
       PREVIOUS_CHANGE=0
@@ -23,13 +23,13 @@ if [ "${curl_exit_code}" = "0" ]; then
       exit 1
     else
       if [ ${PREVIOUS_CHANGE} -lt ${last_change_millis} ]; then
-	logger -t sailing "New SSH key changes for landscape managers (${last_change_millis} newer than ${PREVIOUS_CHANGE})"
-	if update_authorized_keys_for_landscape_managers "${BEARER_TOKEN}" "${BASE_URL}" "${LOGON_USER_HOME}" ; then
-	  logger -t sailing "Updating SSH keys for landscape managers successful; updating ${LAST_CHANGE_FILE}"
-	  echo ${last_change_millis} >${LAST_CHANGE_FILE}
-	else
-	  logger -t sailing "Updating SSH keys for landscape managers failed with exit code $?; not updating ${LAST_CHANGE_FILE}"
-	fi
+    logger -t sailing "New SSH key changes for landscape managers (${last_change_millis} newer than ${PREVIOUS_CHANGE})"
+    if update_authorized_keys_for_landscape_managers "${BEARER_TOKEN}" "${BASE_URL}" "${LOGON_USER_HOME}" ; then
+      logger -t sailing "Updating SSH keys for landscape managers successful; updating ${LAST_CHANGE_FILE}"
+      echo ${last_change_millis} >${LAST_CHANGE_FILE}
+    else
+      logger -t sailing "Updating SSH keys for landscape managers failed with exit code $?; not updating ${LAST_CHANGE_FILE}"
+    fi
       fi
     fi
   else
