b5912: Incorporate groups into build-crontab scripts.

diff --git a/configuration/environments_scripts/build-crontab-and-cp-files b/configuration/environments_scripts/build-crontab-and-cp-files
--- a/configuration/environments_scripts/build-crontab-and-cp-files
+++ b/configuration/environments_scripts/build-crontab-and-cp-files
@@ -8,6 +8,9 @@
 # Within these crontab stubs, are certain string literals, which are replaced: PATH_OF_GIT_HOME_DIR_TO_REPLACE becomes
 # the absolute path to the git home dir, and PATH_OF_HOME_DIR_TO_REPLACE is changed to the path of the home directory
 # in which the crontab will be installed. 
+# Furthermore, within the users folder optional uid, gid and groups files an exist. uid should store the user's uid,
+# gid the group id and groups should have secondary groups (one per line). The secondary groups are added after all users are 
+# created.
 # Useful files are also copied across from the "files" dir within each image type.
 # Finally, the script ends by performing a deamon reload and reenabling all the systemd units in the files directory,
 # so that the correct wants, requires, etc. are installed/linked. Any systemd units, within the mimicked filesystem,
@@ -41,7 +44,20 @@ ENV_TYPE="$1"
 GIT_USER="$2"
 RELATIVE_GIT_DIR_NAME="$3"
 cd "$(dirname "$0")/${ENV_TYPE}"
-if [[ -d "users" && "$CREATE_CRONTABS" == "true" ]]; then
+if [[ -d "groups" ]]; then
+    cd "groups"
+    for group in * ; do
+        [[ -e "$group" ]] || continue
+        echo "CREATING group $group"
+        if [[ -e "$group"/gid ]]; then
+            groupadd --gid $(cat "$group"/gid) "$group"
+        else
+            groupadd "$group"
+        fi
+    done
+    cd ..
+fi
+if [[ -d "users" ]]; then
     cd "users"
     GIT_PATH="$(eval echo $(printf "~%q" "$GIT_USER"))/${RELATIVE_GIT_DIR_NAME}" # The path to the git repo that contains the files needed.
     for dir in $(ls -d */ ); do
@@ -55,9 +71,9 @@ if [[ -d "users" && "$CREATE_CRONTABS" == "true" ]]; then
         fi
         if [[ -f "$USERNAME"/gid ]]; then
             user_GID=$(cat "$USERNAME"/gid)
-            groupadd --gid "$user_GID" "$USERNAME"
             echo "GID => $user_GID"
-
+            groupadd --gid "$user_GID" "$USERNAME"
+            [[ "$?" -eq 0 ]] || echo "Group id or name already exists."
         fi
         if [[ -n "$user_UID" && -n "$user_GID" ]]; then
             adduser --uid "$user_UID" --gid "$user_GID" "$USERNAME"
@@ -68,25 +84,46 @@ if [[ -d "users" && "$CREATE_CRONTABS" == "true" ]]; then
         else
             adduser "$USERNAME"
         fi
-        for group in $(cat "$USERNAME"/groups); do
-            gpasswd --add "$USERNAME" "$group"  
-        done
-        HOME_DIR=$(eval echo $(printf "~%q" "$USERNAME"))   # The path to the home dir of the user whose cronjob will be installed.
-        # Clear the crontab file before assembling it from the snippets:
-        > $HOME_DIR/crontab
-        for crontab in ${USERNAME}/crontab*; do
-	        [[ -e $crontab ]] || continue
-            cat "${crontab}">> $HOME_DIR/crontab
-        done
-        sed -i "s|PATH_OF_GIT_HOME_DIR_TO_REPLACE|${GIT_PATH}|g" "$HOME_DIR"/crontab # Sets correct path to the git repo within the crontab.
-        sed -i "s|PATH_OF_HOME_DIR_TO_REPLACE|${HOME_DIR}|g" "$HOME_DIR"/crontab # Sets the correct path to the home dir of the user whose crontab will be installed.
-        echo "">>$HOME_DIR/crontab  # Adds a newline
-        if [[ "$INSTALL_CRONTAB" == "true" ]]; then    
-            crontab -u ${USERNAME} $HOME_DIR/crontab # Install the crontab in the given user's home dir.
+        id "$USERNAME"
+        if [[ "$?" -eq 0 &&  "$CREATE_CRONTABS" == "true" ]]; then  # 9 is the exit code indicating the username already exists.
+            HOME_DIR=$(eval echo $(printf "~%q" "$USERNAME"))   # The path to the home dir of the user whose cronjob will be installed.
+            # Clear the crontab file before assembling it from the snippets:
+            > $HOME_DIR/crontab
+            for crontab in ${USERNAME}/crontab*; do
+                [[ -e $crontab ]] || continue
+                cat "${crontab}">> $HOME_DIR/crontab
+            done
+            sed -i "s|PATH_OF_GIT_HOME_DIR_TO_REPLACE|${GIT_PATH}|g" "$HOME_DIR"/crontab # Sets correct path to the git repo within the crontab.
+            sed -i "s|PATH_OF_HOME_DIR_TO_REPLACE|${HOME_DIR}|g" "$HOME_DIR"/crontab # Sets the correct path to the home dir of the user whose crontab will be installed.
+            echo "">>$HOME_DIR/crontab  # Adds a newline
+            if [[ "$INSTALL_CRONTAB" == "true" ]]; then
+                crontab -u ${USERNAME} $HOME_DIR/crontab # Install the crontab in the given user's home dir.
+            fi
         fi
-        echo "*** FINISHED USER $USERNAME ***"
+        echo "****** finished user ******"
+    done
+    # Add to groups after all the groups exist.
+    for dir in $(ls -d */ ); do
+        USERNAME=$(echo "$dir" | sed "s/\/$//") # Dirname is the username. The trailing slash is removed.
+        [[ -e "$USERNAME"/groups ]] || continue
+        echo "ADDING $USERNAME TO THE GROUPS SPECIFIED IN THEIR 'groups' FILE"
+        for group in $(cat "$USERNAME"/groups); do
+            gpasswd --add "$USERNAME" "$group"
+        done
     done
     cd .. # exits users folder, which is essential for the next commands
+fi
+# Add users to groups, specified in ENVIRONMENT_TYPE/groups/GROUP/users. Used if groups exist which aren't directly related to a user.
+if [[ -d "groups" ]]; then
+    cd "groups"
+    for group in * ; do
+        [[ -e "$group"/users ]] || continue
+        echo "ADDING USERS IN 'users' FILE TO GROUP $group"
+        for user in $(cat "$group"/users); do
+            gpasswd -a "$user" "$group"
+        done
+    done
+    cd ..
 fi
 if [[ "$COPY_FILES" == "true" && -d "files" ]]; then
     cd "files"
